AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-notify

Globals:
  Function:    
    MemorySize: 128
    Architectures:
      - x86_64
    Runtime: nodejs20.x
    Timeout: 30
    Tracing: Active     
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Parameters:
  Email:
    Type: String
    Description: Email address to receive notifications
  StageName:
    Type: String
    Default: Prod
    Description: The stage name for the API Gateway

Resources:
  #API GATEWAY 
  NotifyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: NotifyRestApi
      StageName: !Ref StageName
      Description: Notify API
      Cors: 
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"  
      Models:
        NotifyValidationModel:
          type: object
          required: 
            - notifications
          properties:
            notifications:
              type: array 
              items:
                type: object
                required: 
                  - priority
                  - message
                  - userId
                properties:
                  priority:
                    type: string
                    enum: 
                      - HIGH
                      - MEDIUM
                      - LOW
                  message:
                    type: string
                    minLength: 1
                    maxLength: 255
                  userId:
                    type: string 
                    format: uuid       
      Tags:
        Name: NotifyRestApi
        Environment: !Ref AWS::StackName
        Project: Notify
        Version: 1.0.0
        Description: Notify API 

  # SNS
  SNSNotifyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NotifyTopic
      TopicName: NotifyTopic
      Tags:
        - Key: Name
          Value: NotifyTopic
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify Topic
  
  SNSNotifyAlert:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NotifyAlertTopic
      TopicName: NotifyAlertTopic
      Tags:
        - Key: Name
          Value: NotifyAlertTopic
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify Alert Topic
  
  SNSNotifyHighPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyHighPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - HIGH 
  
  SNSNotifyMediumPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyMediumPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - MEDIUM
  
  SNSNotifyLowPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyLowPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - LOW  

  SNSNotifyAlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSNotifyAlert
      Endpoint: !Ref Email

  # SQS
  SQSNotifyHighPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:     
      QueueName: NotifyHighPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SQSNotifyDLQ.Arn
        maxReceiveCount: 5
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: NotifyHighPriorityQueue
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify High Priority Queue
  
  SQSNotifyMediumPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyMediumPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SQSNotifyDLQ.Arn
        maxReceiveCount: 5
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: NotifyMediumPriorityQueue
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify Medium Priority Queue
  
  SQSNotifyLowPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyLowPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SQSNotifyDLQ.Arn
        maxReceiveCount: 5
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: NotifyLowPriorityQueue
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify Low Priority Queue
  
  SQSNotifyHighPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyHighPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyHighPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic

  SQSNotifyMediumPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyMediumPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyMediumPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic
  
  SQSNotifyLowPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyLowPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: sns.amazonaws.com
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyLowPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic

  SQSNotifyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSNotifyDLQ
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: SQSNotifyDLQ
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify DLQ 

  # Lambda  
  NotifyValidationFunction:
    Type: AWS::Serverless::Function  
    Properties:    
      FunctionName: NotifyValidationFunction
      CodeUri: notify-validation/
      Handler: app.handler
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSNotifyTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSNotifyTopic 
      Events:
        ApiEvent:
          Type: Api
          Properties: 
            RestApiId: !Ref NotifyRestApi
            Path: /notifications
            Method: post 
            RequestModel:
              Model: NotifyValidationModel
              Required: True
              ValidateBody: True
              ValidateParameters: True
      Tags:
        Name: NotifyValidationFunction
        Environment: !Ref AWS::StackName
        Project: Notify
        Version: 1.0.0
        Description: Notify Validation Function
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  
  NotifyProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotifyProcessFunction
      CodeUri: notify-process/
      Handler: app.handler  
      Policies: 
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyHighPriorityQueue
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyMediumPriorityQueue
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyLowPriorityQueue
        - DynamoDBCrudPolicy:
            TableName: !Ref NotifyDbTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSNotifyAlert.TopicName  
      Environment:
        Variables: 
          DYNAMODB_TABLE_NAME: !Ref NotifyDbTable
          SNS_TOPIC_ARN: !Ref SNSNotifyAlert 
      Events:
        SQSNotifyHighPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyHighPriorityQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
        SQSNotifyMediumPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyMediumPriorityQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
        SQSNotifyLowPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyLowPriorityQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Tags:
        Name: NotifyProcessFunction
        Environment: !Ref AWS::StackName
        Project: Notify
        Version: 1.0.0
        Description: Notify Process Function
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  NotifyProcessDLQFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotifyProcessDLQFunction
      CodeUri: notify-process-dlq/
      Handler: app.handler   
      Policies: 
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyDLQ 
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSNotifyAlert.TopicName  
      Environment:
        Variables:  
          SNS_TOPIC_ARN: !Ref SNSNotifyAlert 
      Events:
        SQSNotifyDLQevent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyDLQ.Arn
            BatchSize: 10 
      Tags:
        Name: NotifyProcessDLQFunction
        Environment: !Ref AWS::StackName
        Project: Notify
        Version: 1.0.0
        Description: Notify Process DLQ Function
        
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  NotificationListFunction:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: NotifyListFunction
      CodeUri: notify-list/
      Handler: app.handler
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref NotifyDbTable
      Environment:
        Variables: 
          DYNAMODB_TABLE_NAME: !Ref NotifyDbTable 
      Events:
        NotificationListEvent:
          Type: Api
          Properties:
            RestApiId: !Ref NotifyRestApi
            Path: /notifications/{userId}
            Method: GET

    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  # DynamoDB
  NotifyDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotifyDynamoTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Name
          Value: NotifyDynamoTable
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify DynamoDB Table
  
  # WAF
  NotifyWAFWebACL:
    Type: AWS::WAFv2::WebACL 
    Properties:
      Name: NotifyWAFWebACL
      Description: Notify WAF Web ACL
      Scope: REGIONAL
      DefaultAction:
        Allow: {} 
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: NotifyWAFWebACL
        SampledRequestsEnabled: true
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
            SampledRequestsEnabled: true
      Tags:
        - Key: Name
          Value: NotifyWAFWebACL
        - Key: Environment
          Value: !Ref AWS::StackName
        - Key: Project
          Value: Notify
        - Key: Version
          Value: 1.0.0
        - Key: Description
          Value: Notify WAF Web ACL 
  
  NotifyWAFWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation 
    Properties: 
      ResourceArn: !Sub 
          - arn:aws:apigateway:${AWS::Region}::/restapis/${NotifyRestApi}/stages/${StageName}
          - NotifyRestApi: !Ref NotifyRestApi
            StageName: !Ref NotifyRestApi.Stage
      WebACLArn: !GetAtt NotifyWAFWebACL.Arn   